import flet as ft

PANEL_CONTENT_MARGIN = 20
MARGIN_BETWEEN_PANELS = 15
ICON_COLOR = ft.Colors.ON_PRIMARY_CONTAINER
ICON_BAR_COLOR = ft.Colors.PRIMARY_CONTAINER
PANEL_TEXT_COLOR = ft.Colors.ON_SURFACE_VARIANT
PANEL_BG_COLOR = ft.Colors.SURFACE_CONTAINER
HEADER_TEXT_COLOR = ft.Colors.ON_SURFACE_VARIANT
HEADER_BG_COLOR = ft.Colors.SURFACE_CONTAINER_HIGHEST